### ISSUE TITLE
Getting error as 

### ISSUE THREAD

**Issue by prachi3011** [startingwithseleniumwebdriver/RealTimeReport#12]
While importing project got error as ..
The method marshal(Object, Result) in the type Marshaller is not applicable for the arguments (ConsolidatedResult, File)	CreateXML.java	

Please respond asap

**Comment by startingwithseleniumwebdriver** [comment]
`Marshaller` has multiple overridden methods for `marshal()`. Please use `marshal(Object, File)` if you are modifying existing for your project. This issue is not something directly related to our project. So, closing.
